name: xcodeproj
description: A library for reading and modifying XCode projects.
version: 0.2.3
homepage: https://github.com/appsup-dart/xcodeproj

environment:
  sdk: '>=2.12.0 <3.0.0'
  

dependencies:
  petitparser: ^5.0.0
  xml: ^6.1.0
  snapshot: ^0.2.0
  crypto: ^3.0.0
  path: ^1.8.0
  quiver: ^3.0.0
  collection: ^1.15.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
