name: xcodeproj
description: A library for reading and modifying XCode projects.
version: 0.2.4+1
homepage: https://github.com/appsup-dart/xcodeproj
repository: https://github.com/appsup-dart/xcodeproj

environment:
  sdk: '>=3.0.0 <4.0.0'
  

dependencies:
  petitparser: '>=5.0.0 <8.0.0'
  xml: ^6.0.0
  snapshot: ^0.2.0
  crypto: ^3.0.0
  path: ^1.8.0
  quiver: ^3.0.0
  collection: ^1.15.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0
  melos: ^7.0.0

melos:
  useRootAsPackage: true

  ide:
    intellij: false

  command:
    version:
      linkToCommits: true
      workspaceChangelog: false

  scripts:
    preversion: 
      exec: dart test -j 1